#!/bin/sh

a=`cat /proc/cpuinfo | grep BogoMIPS | head -1 | awk {' print $3'} | awk '{printf "%0.1f %s\n", $1/100}' | awk '{printf "%s\n", $1*50}'`

b=`cat /proc/cpuinfo | grep processor | wc -l`

d=`cat /proc/dmu/temperature | head -1 | awk '{ print substr($4,1,length($4)-2)}'`

e=`wl -i eth1 phy_tempsense | awk {' print $1'}`

f=`wl -i eth2 phy_tempsense | awk {' print $1'}`

g=`smartctl -s on -x /dev/sda | grep "Current Temperature" | awk {' print $3'}`

if [ $b == "0" ]; then
c="single"
else
c="dual"
fi

if [ ! $d ]; then d="N/A"; fi
if [ ! $e ]; then e="N/A"; fi
if [ ! $f ]; then f="N/A"; fi
if [ ! $g ]; then g="N/A"; fi

echo "cpu MHz : $a MHz ($c-core)" > /tmp/sysinfo-helper
echo "cpu Temp : $d" >> /tmp/sysinfo-helper
echo "wl0 Temp : $e" >> /tmp/sysinfo-helper
echo "wl1 Temp : $f" >> /tmp/sysinfo-helper
echo "hdd Temp : $g" >> /tmp/sysinfo-helper

